// Code generated by mockery v2.16.0. DO NOT EDIT.

package http

import mock "github.com/stretchr/testify/mock"

// HttpServer is an autogenerated mock type for the HttpServer type
type HttpServer struct {
	mock.Mock
}

type HttpServer_Expecter struct {
	mock *mock.Mock
}

func (_m *HttpServer) EXPECT() *HttpServer_Expecter {
	return &HttpServer_Expecter{mock: &_m.Mock}
}

// StartServer provides a mock function with given fields:
func (_m *HttpServer) StartServer() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HttpServer_StartServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartServer'
type HttpServer_StartServer_Call struct {
	*mock.Call
}

// StartServer is a helper method to define mock.On call
func (_e *HttpServer_Expecter) StartServer() *HttpServer_StartServer_Call {
	return &HttpServer_StartServer_Call{Call: _e.mock.On("StartServer")}
}

func (_c *HttpServer_StartServer_Call) Run(run func()) *HttpServer_StartServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *HttpServer_StartServer_Call) Return(_a0 error) *HttpServer_StartServer_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewHttpServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewHttpServer creates a new instance of HttpServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHttpServer(t mockConstructorTestingTNewHttpServer) *HttpServer {
	mock := &HttpServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
