openapi: 3.0.3
info:
  title: Toy Car Api
  description: |-
    This is the toy car api
  version: 0.1.0
servers:
  - url: http://localhost:3000
tags:
  - name: Toy
    description: Toy Car
paths:
  /toy:
    get:
      tags:
        - Toy
      summary: Fetch toy car position
      description: Fetch toy car position in the tabletop and its direction
      operationId: getToy
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToyPosition"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /toy/place:
    post:
      tags:
        - Toy
      summary: Send place command
      description: Send Command to place the car in the tabletop
      operationId: placeToy
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ToyCommand"
        required: true
      responses:
        "202":
          description: Command Registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToyPosition"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /toy/move:
    post:
      tags:
        - Toy
      summary: Send move command
      description: Send Command to move the car in the tabletop
      operationId: moveToy
      responses:
        "202":
          description: Command Registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToyPosition"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /toy/left:
    post:
      tags:
        - Toy
      summary: Send left command
      description: Send Command to turn left the car on the tabletop
      operationId: leftToy
      responses:
        "202":
          description: Command Registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToyPosition"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
  /toy/right:
    post:
      tags:
        - Toy
      summary: Send right command
      description: Send Command to turn right the car on the tabletop
      operationId: rigthToy
      responses:
        "202":
          description: Command Registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToyPosition"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
components:
  schemas:
    BadRequest:
      type: object
      properties:
        message:
          type: string
          example: Toy isnt placed in the tabletop
    ToyPosition:
      type: object
      properties:
        x:
          type: integer
          format: int64
          example: 10
        y:
          type: integer
          format: int64
          example: 10
        direction:
          type: string
          enum:
            - SOUTH
            - NORTH
            - WEST
            - EAST
    ToyCommand:
      type: object
      required:
        - command
        - x
        - y
        - direction
      properties:
        command:
          type: string
          enum:
            - PLACE
            - MOVE
            - LEFT
            - RIGHT
        x:
          type: integer
          format: int64
          example: 10
        y:
          type: integer
          format: int64
          example: 10
        direction:
          type: string
          enum:
            - SOUTH
            - NORTH
            - WEST
            - EAST
