openapi: 3.0.3
info:
  title: Toy Car Api
  description: |-
    This is the toy car api
  version: 0.1.0
servers:
  - url: http://localhost:3000
tags:
  - name: Toy
    description: Toy Car
paths:
  /toy:
    get:
      tags:
        - Toy
      summary: Fetch toy car position
      description: Fetch toy car position in the tabletop and its direction
      operationId: getPet
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToyPosition"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
    post:
      tags:
        - Toy
      summary: Send commands to control the toy car
      description: Send commands like PLACE, MOVE, LEFT and RIGHT to control the toy car
      operationId: commandToy
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ToyCommand"
        required: true
      responses:
        "202":
          description: Command Registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ToyPosition"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BadRequest"
components:
  schemas:
    BadRequest:
      type: object
      properties:
        message:
          type: string
          example: Toy isnt placed in the tabletop
    ToyPosition:
      type: object
      properties:
        x:
          type: integer
          format: int64
          example: 10
        y:
          type: integer
          format: int64
          example: 10
        direction:
          type: string
          enum:
            - SOUTH
            - NORTH
            - WEST
            - EAST
    ToyCommand:
      type: object
      required:
        - command
      properties:
        command:
          type: string
          enum:
            - PLACE
            - MOVE
            - LEFT
            - RIGHT
        x:
          type: integer
          format: int64
          example: 10
          description: Required for PLACE command
        y:
          type: integer
          format: int64
          example: 10
          description: Required for PLACE command
        direction:
          type: string
          description: Required for PLACE command
          enum:
            - SOUTH
            - NORTH
            - WEST
            - EAST
